version: "3.7"

services:
  web:
    build: .
    container_name: financial
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py get_raw_data && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports: 
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./financial:/financial
      
  postgres:
      image: postgres:alpine3.17
      restart: always
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
      ports:
        - "5432:5432"

  